### ISSUE TITLE
Windows DNS search suffix list is incomplete

### ISSUE THREAD

**Issue by PatrickLang** [Azure/acs-engine#3643]
**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: all

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**: Kubernetes

**What happened**:

On Windows, the DNS search suffix list only contains the pod namespace. If a service is exposed in another namespace, it can only be resolved using a FQDN. The default and kube-system namespaces are never searched for example.

**Tasks**

This issue requires multiple steps in multiple repos to fix it:

- [ ] Fix for https://github.com/kubernetes/kubernetes/issues/66801
- [ ] Update to Azure-CNI
- [ ] Update in this repo to deploy updated Kubernetes and Azure-CNI builds

Other related issues:

- https://github.com/Azure/acs-engine/issues/3143 - this issue reported that DNS search suffix was blank. It's no longer blank, but its still incomplete
