### ISSUE TITLE
Cleanup Windows installations

### ISSUE THREAD

**Issue by PatrickLang** [Azure/acs-engine#3851]
This is list to track what needs to be done to make Windows work better with upstream builds.

First Step - support upstream binaries
- [x] Add new parameter `$global:KubeBinariesReleaseUrl` to parts\k8s\kuberneteswindowssetup.ps1 to download [node binaries] #4008 (https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md#node-binaries-1) and [client binaries](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md#client-binaries-1). Install those instead of binaries from `$global:KubeBinariesSASURL` 
- [x] Same for Azure CNI #4007 
- [ ] Add ContainerD support #4006 
- [ ] Remove support for 1.9 in k8s_versions.go so we can delete NSSM
- [ ] Remove dependency on NSSM. Use new flags added in https://github.com/kubernetes/kubernetes/pull/60144

Second Step - don't break kubetest Azure provider
- [ ] Update https://github.com/kubernetes/test-infra/pull/7625 or issue new PR if it's not merged. Remove the step to build the zip, and instead set the path to Kubernetes binaries

Third Step - clean up

- [ ] Delete code in parts\k8s\kuberneteswindowssetup.ps1 related to NSSM and zip file
- [ ] Delete acs-engine\scripts\build-windows-k8s.sh from this tree

--- 

**History on acs-engine\scripts\build-windows-k8s.sh**

This script was written before Kubernetes had upstream builds for Windows (kubelet.exe, kube-proxy.exe, kubectl.exe). It was designed to pull sources from git, apply some cherry-picks, build the binaries, download NSSM, and package everything up into a ZIP.
